### ISSUE TITLE
stdnum.se.personnummer is_valid - exception is thrown

### ISSUE THREAD

**Issue by balderman1** [arthurdejong/python-stdnum#188]
I have code that calls the is_valid method of  stdnum.se.personnummer.
The input I am sending is “breaking” the birthday calculation and I believe should be fixed.
The code below reproduces the issue

```
from stdnum.se.personnummer import is_valid

is_valid('19670-19-9535')
```

The output is:

Traceback (most recent call last):
  File "C:/dev/projects/waf-ai-repo/reproduce_stdnum_issue.py", line 3, in <module>
    is_valid('19670-19-9535')
  File "C:\dev\tools\python371\lib\site-packages\stdnum\se\personnummer.py", line 118, in is_valid
    return bool(validate(number))
  File "C:\dev\tools\python371\lib\site-packages\stdnum\se\personnummer.py", line 110, in validate
    get_birth_date(number)
  File "C:\dev\tools\python371\lib\site-packages\stdnum\se\personnummer.py", line 73, in get_birth_date
    month = int(number[4:6])
ValueError: invalid literal for int() with base 10: '0-'

**Comment by arthurdejong** [comment]
Thanks for pointing this out. The `is_valid()` function should indeed never raise an exception (similarly `validate()` should only raise subclasses of `ValidationError`).

Just to confirm: 19670-19-9535 only has 11 digits so should not be considered valid, can you confirm?

**Comment by balderman1** [comment]
Confirmed
Thanks

**Comment by arthurdejong** [comment]
Thanks!
