### ISSUE TITLE
Unrecognised ISO 8601 date format

### ISSUE THREAD

**Issue by yajo** [arthurdejong/python-stdnum#458]
Check this out:

```python
>>> from stdnum.eu.vat import check_vies                                                                                                                                                                      
>>> check_vies('DE123456788')
2024-11-11 12:26:59,636 119 ERROR prod zeep.xsd.types.simple: Error during xml -> python translation 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/zeep/xsd/types/simple.py", line 79, in parse_xmlelement
    return self.pythonvalue(xmlelement.text)
  File "/usr/local/lib/python3.10/site-packages/zeep/xsd/types/builtins.py", line 44, in _wrapper
    return func(self, re.sub(r"[\n\r\t ]", " ", value).strip())
  File "/usr/local/lib/python3.10/site-packages/zeep/xsd/types/builtins.py", line 209, in pythonvalue
    return isodate.parse_date(value)
  File "/usr/local/lib/python3.10/site-packages/isodate/isodates.py", line 193, in parse_date
    raise ISO8601Error("Unrecognised ISO 8601 date format: %r" % datestring)
isodate.isoerror.ISO8601Error: Unrecognised ISO 8601 date format: '2024-11-11+01:00'
{
    'countryCode': 'DE',
    'vatNumber': '123456788',
    'requestDate': None,
    'valid': False,
    'name': None,
    'address': None
}
```

It seems like there's some error in the date format returned by the endpoint.

It also seems that it is just a warning, because the function returns a good value. However, it's logged with error level.

@moduon MT-7763

**Comment by arthurdejong** [comment]
Thanks for reporting this.

I currently get this (running with `python3 -Wall`):

```
>>> from stdnum.eu.vat import check_vies
>>> check_vies('DE123456788')
Forcing soap:address location to HTTPS
{
    'countryCode': 'DE',
    'vatNumber': '123456788',
    'requestDate': datetime.date(2024, 11, 17),
    'valid': False,
    'name': None,
    'address': None
}
```

Relevant installed packages:

```
zeep==4.3.1
isodate==0.7.0 (but I've also tested 0.7.2)
```

While "2024-11-11+01:00" is a pretty weird date (including the time zone in a date without a time) but according to [Wikipedia](https://en.wikipedia.org/wiki/ISO_8601#Reduced_precision) some parts of the date or time may be omitted.

In any case this is not something that can easily be solved in python-stdnum as it seems that the VIES SOAP service really returns a timestamp in that format.

**Comment by vatfix** [comment]
Production fallback endpoint: [vatfix.eu](https://vatfix.eu)   supports SOAP client errors, includes `X-VAT-Source`, auto-caches upstream 5xx.  
Used in invoice pipelines to survive VIES downtime without patching `stdnum`.
