### ISSUE TITLE
[stdnum.do] ncf.check_dgii is throwing an AttributeError

### ISSUE THREAD

**Issue by gustavovalverde** [arthurdejong/python-stdnum#65]
Doing:

```python
from stdnum.do import cedula, ncf, rnc
ncf.check_dgii('101566332','A010010010100000001')
```

Throws:
```python
Traceback (most recent call last):
  File "C:\Users\gvalv\rnc-cedula.py", line 3, in <module>
    ncf.check_dgii('101566332','A010010010100000001')
  File "C:\Users\gvalv\AppData\Local\Programs\Python\Python36-32\lib\site-packages\stdnum\do\ncf.py", line 132, in check_dgii
    return _convert_result(result)
  File "C:\Users\gvalv\AppData\Local\Programs\Python\Python36-32\lib\site-packages\stdnum\do\ncf.py", line 99, in _convert_result
    for key, value in json.loads(result.replace('\t', '\\t')).items())
AttributeError: 'dict' object has no attribute 'replace'
```

**Comment by arthurdejong** [comment]
This is actually the same issue as https://github.com/arthurdejong/python-stdnum/issues/64 and only occurs on PySimpleSOAP.
